### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by starptr** [H5O2plus/Eigen-examples#1]
Things to do (updated periodically):
- [x] understand numerical linear algebra
- [x] demonstrate how to use Eigen
- [x] represent a matrix & a vector with Eigen
- [x] solve matrix multiplication with Eigen
- [x] solve linear equation system with Eigen
- [x] fit a line to dataset using linear least squares with Eigen
- [x] validate the above regression with another method
- [x] create a wrapper to solve any linear equation system where coefficients are given as CSV file
- [x] find rank, nullity, dimension of linear transformations
- [x] find eigenvalues and eigenvectors, both real and complex
- [ ] publish a short review paper
- [ ] create a slideshow
